version: "0.2"
language: en-GB
useGitignore: true
ignorePaths:
  - "**/node_modules"
  - "**/pnpm-lock.yaml"
  - "**/*.svg"
dictionaryDefinitions: []
dictionaries: []
words:
  - Flightcontrol
  - geist
  - Hostinger
  - Lifecycles
  - logomark
  - pasteable
  - Replit
  - SDLC
  - Sephnescence
  - signups
  - Turbopack
  - unpushed
  - unrs
  - utdir
ignoreWords: []
import: []
