version: "0.2"
language: en-GB
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - Flightcontrol
  - Hostinger
  - Lifecycles
  - pasteable
  - Replit
  - SDLC
  - Sephnescence
  - signups
  - Turbopack
  - utdir
ignoreWords: []
import: []
